In [1]:
import numpy as np

In [2]:
np.arange(0,9,1).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.random.randint(10,50,10)

array([15, 11, 31, 32, 32, 45, 48, 26, 20, 10])

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
hilbert_matrix = 1 / np.array([[(i+j - 1) for i in range(1,6)] for j in range(1,6)], dtype=float)

In [6]:
hilbert_matrix

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [7]:
1 / (np.arange(1,6) + np.arange(0,5)[:, np.newaxis])

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [8]:
1 / (np.arange(1,6) + np.arange(0,5).reshape(5,1))

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [9]:
hubert_matrix = 1 / (np.arange(1,6) + np.arange(0,5).reshape(5,1))

In [10]:
hubert_matrix.itemsize

8

In [11]:
def get_magic_square(N):
    matrix = np.zeros((N,N))
    x, y = 0, int((N-1)/2)
    
    x = N
    y = int((N - 1) / 2)
    
    n = 1
    while n != pow(N, 2) + 1:
        if matrix[-x % N, y %N ] == 0:
            matrix[-x % N, y % N] = n
            n += 1
            x += 1
            y += 1
        else:
            x -= 2
            y -= 1
    print(matrix)
    return matrix

In [12]:
res = get_magic_square(10)

[[ 63.  75.  87.  99.   1.  13.  25.  37.  49.  51.]
 [ 74.  86.  98.  10.  12.  24.  36.  48.  60.  62.]
 [ 85.  97.   9.  11.  23.  35.  47.  59.  61.  73.]
 [ 96.   8.  20.  22.  34.  46.  58.  70.  72.  84.]
 [  7.  19.  21.  33.  45.  57.  69.  71.  83.  95.]
 [ 18.  30.  32.  44.  56.  68.  80.  82.  94.   6.]
 [ 29.  31.  43.  55.  67.  79.  81.  93.   5.  17.]
 [ 40.  42.  54.  66.  78.  90.  92.   4.  16.  28.]
 [ 41.  53.  65.  77.  89.  91.   3.  15.  27.  39.]
 [ 52.  64.  76.  88. 100.   2.  14.  26.  38.  50.]]


In [13]:
res.shape

(10, 10)

In [14]:
res.resize((5,20))

In [16]:
res.reshape((10,10))

array([[ 63.,  75.,  87.,  99.,   1.,  13.,  25.,  37.,  49.,  51.],
       [ 74.,  86.,  98.,  10.,  12.,  24.,  36.,  48.,  60.,  62.],
       [ 85.,  97.,   9.,  11.,  23.,  35.,  47.,  59.,  61.,  73.],
       [ 96.,   8.,  20.,  22.,  34.,  46.,  58.,  70.,  72.,  84.],
       [  7.,  19.,  21.,  33.,  45.,  57.,  69.,  71.,  83.,  95.],
       [ 18.,  30.,  32.,  44.,  56.,  68.,  80.,  82.,  94.,   6.],
       [ 29.,  31.,  43.,  55.,  67.,  79.,  81.,  93.,   5.,  17.],
       [ 40.,  42.,  54.,  66.,  78.,  90.,  92.,   4.,  16.,  28.],
       [ 41.,  53.,  65.,  77.,  89.,  91.,   3.,  15.,  27.,  39.],
       [ 52.,  64.,  76.,  88., 100.,   2.,  14.,  26.,  38.,  50.]])

In [18]:
b = res.resize((10,10))

In [22]:
b = res.reshape((10,10))

In [29]:
b.flatten()

array([ 63.,  75.,  87.,  99.,   1.,  13.,  25.,  37.,  49.,  51.,  74.,
        86.,  98.,  10.,  12.,  24.,  36.,  48.,  60.,  62.,  85.,  97.,
         9.,  11.,  23.,  35.,  47.,  59.,  61.,  73.,  96.,   8.,  20.,
        22.,  34.,  46.,  58.,  70.,  72.,  84.,   7.,  19.,  21.,  33.,
        45.,  57.,  69.,  71.,  83.,  95.,  18.,  30.,  32.,  44.,  56.,
        68.,  80.,  82.,  94.,   6.,  29.,  31.,  43.,  55.,  67.,  79.,
        81.,  93.,   5.,  17.,  40.,  42.,  54.,  66.,  78.,  90.,  92.,
         4.,  16.,  28.,  41.,  53.,  65.,  77.,  89.,  91.,   3.,  15.,
        27.,  39.,  52.,  64.,  76.,  88., 100.,   2.,  14.,  26.,  38.,
        50.])

In [36]:
b

array([[ 63.,  75.,  87.,  99.,   1.,  13.,  25.,  37.,  49.,  51.],
       [ 74.,  86.,  98.,  10.,  12.,  24.,  36.,  48.,  60.,  62.],
       [ 85.,  97.,   9.,  11.,  23.,  35.,  47.,  59.,  61.,  73.],
       [ 96.,   8.,  20.,  22.,  34.,  46.,  58.,  70.,  72.,  84.],
       [  7.,  19.,  21.,  33.,  45.,  57.,  69.,  71.,  83.,  95.],
       [ 18.,  30.,  32.,  44.,  56.,  68.,  80.,  82.,  94.,   6.],
       [ 29.,  31.,  43.,  55.,  67.,  79.,  81.,  93.,   5.,  17.],
       [ 40.,  42.,  54.,  66.,  78.,  90.,  92.,   4.,  16.,  28.],
       [ 41.,  53.,  65.,  77.,  89.,  91.,   3.,  15.,  27.,  39.],
       [ 52.,  64.,  76.,  88., 100.,   2.,  14.,  26.,  38.,  50.]])

In [38]:
c = b.copy()

In [48]:
c.reshape((20,10)).T

array([[ 63.,  74.,  85.,  96.,   7.,  18.,  29.,  40.,  41.,  52.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 75.,  86.,  97.,   8.,  19.,  30.,  31.,  42.,  53.,  64.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 87.,  98.,   9.,  20.,  21.,  32.,  43.,  54.,  65.,  76.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 99.,  10.,  11.,  22.,  33.,  44.,  55.,  66.,  77.,  88.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 13.,  24.,  35.,  46.,  57.,  68.,  79.,  90.,  91.,   2.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 25.,  36.,  47.,  58.,  69.,  80.,  81.,  92.,   3.,  14.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 37.,  48.,  59.,  70.,  71.,  82

In [49]:
aaa = np.array([[1,2,3],[4,5,6]])
bbb = aaa.T 

In [53]:
aaa

array([[ 1,  2,  3],
       [ 4, 99,  6]])

In [54]:
bbb

array([[ 1,  4],
       [ 2, 99],
       [ 3,  6]])

In [52]:
aaa[1,1] = 99

In [56]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [57]:
ar =  np.ones((3,3))

In [59]:
ar2 = np.vstack((ar, np.array([2,2,2])))

In [72]:
add_col = np.array([[3,3,3,3]]).T

In [73]:
print(ar2.shape, add_col.shape)

(4, 3) (4, 1)


In [77]:
ar3 = np.hstack((ar2, add_col))

In [79]:
np.concatenate((ar2, add_col), axis=1)

array([[1., 1., 1., 3.],
       [1., 1., 1., 3.],
       [1., 1., 1., 3.],
       [2., 2., 2., 3.]])

In [83]:
arr = np.arange(1,49).reshape(3,4,4)

In [121]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [85]:
arr[0,2,:]

array([ 9, 10, 11, 12])

In [86]:
arr[-1,:,:]

array([[33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48]])

In [87]:
arr[:,1,0:2]

array([[ 5,  6],
       [21, 22],
       [37, 38]])

In [100]:
arr[2,:,-1:-3:-1]

array([[36, 35],
       [40, 39],
       [44, 43],
       [48, 47]])

In [102]:
arr[:,::-1,0]

array([[13,  9,  5,  1],
       [29, 25, 21, 17],
       [45, 41, 37, 33]])

In [130]:
arr.min(axis=(1,2,))

array([ 1, 17, 33])

In [103]:
years = np.array([1900,1904,1990,1993,2000,2014,2016,2100])

In [120]:
years[((years % 4 == 0) & (years % 100 != 0)) | ((years % 4 == 0) & (years % 400 == 0))]

array([1904, 2000, 2016])

In [142]:
matrix = np.concatenate((np.linspace(100,190,10, dtype=int).reshape(2,5),
                         np.linspace(10,19,10, dtype=int).reshape(2,5),
                         np.linspace(0,9,10, dtype=int).reshape(2,5))).reshape(3,2,5)

In [143]:
matrix

array([[[100, 110, 120, 130, 140],
        [150, 160, 170, 180, 190]],

       [[ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19]],

       [[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]]])

In [187]:
a = np.random.randint(10,99,60).reshape(2,5,6)
a

array([[[70, 22, 68, 78, 27, 30],
        [36, 80, 11, 39, 88, 66],
        [90, 66, 67, 86, 91, 33],
        [56, 57, 46, 32, 55, 24],
        [16, 21, 48, 18, 30, 72]],

       [[21, 58, 50, 83, 55, 51],
        [61, 35, 23, 96, 64, 87],
        [30, 43, 40, 42, 28, 56],
        [57, 71, 34, 26, 96, 15],
        [47, 63, 41, 98, 48, 12]]])

In [198]:
b = a.copy()
b.sort(axis = 2)
b

array([[[22, 27, 30, 68, 70, 78],
        [11, 36, 39, 66, 80, 88],
        [33, 66, 67, 86, 90, 91],
        [24, 32, 46, 55, 56, 57],
        [16, 18, 21, 30, 48, 72]],

       [[21, 50, 51, 55, 58, 83],
        [23, 35, 61, 64, 87, 96],
        [28, 30, 40, 42, 43, 56],
        [15, 26, 34, 57, 71, 96],
        [12, 41, 47, 48, 63, 98]]])

In [199]:
b = a.copy()
b.sort(axis = -1)
b

array([[[22, 27, 30, 68, 70, 78],
        [11, 36, 39, 66, 80, 88],
        [33, 66, 67, 86, 90, 91],
        [24, 32, 46, 55, 56, 57],
        [16, 18, 21, 30, 48, 72]],

       [[21, 50, 51, 55, 58, 83],
        [23, 35, 61, 64, 87, 96],
        [28, 30, 40, 42, 43, 56],
        [15, 26, 34, 57, 71, 96],
        [12, 41, 47, 48, 63, 98]]])

In [181]:
print(a[abs(a-v).argmin()])

46


In [208]:
arr50 = np.random.randint(1,10, 25).reshape(5,5)
arr50

array([[3, 1, 8, 4, 2],
       [4, 6, 8, 8, 7],
       [3, 3, 5, 7, 4],
       [3, 5, 7, 4, 9],
       [4, 7, 6, 9, 7]])

In [210]:
arr50[arr50[:,2].argsort()]

array([[3, 3, 5, 7, 4],
       [4, 7, 6, 9, 7],
       [3, 5, 7, 4, 9],
       [3, 1, 8, 4, 2],
       [4, 6, 8, 8, 7]])

In [223]:
np.any(arr50 == 5, axis=0)

array([False,  True,  True, False, False])

In [224]:
a = np.zeros(5, dtype='int8, float32, complex')
a

array([(0, 0., 0.+0.j), (0, 0., 0.+0.j), (0, 0., 0.+0.j), (0, 0., 0.+0.j),
       (0, 0., 0.+0.j)],
      dtype=[('f0', 'i1'), ('f1', '<f4'), ('f2', '<c16')])

In [227]:
dt = np.dtype([('time','f8'),('signal','i4')])
b = np.zeros(5, dtype=dt)
b

array([(0., 0), (0., 0), (0., 0), (0., 0), (0., 0)],
      dtype=[('time', '<f8'), ('signal', '<i4')])

In [229]:
b['time'] = np.random.randint(5,14,5)
print(b['time'])

[8. 7. 8. 9. 9.]


In [231]:
b['time'].mean()

8.2

# Structured arrays

In [292]:
data = """Bowhead whale 9000 60
Blue whale 20000 120
Fin whale 100000 70
Pacific white-sided dolphin 1000000 0.15
Killer whale 100000 4.5
Sperm whale 2000000 50
North Atlantic right whale 300 75
Southern right whale 7000 70"""

In [300]:
dt = np.dtype([('Name','U30'),('Population','int32'),('Mass/tonnes', 'float32')])
ex57 = np.zeros(0, dtype=dt)
ex57

array([],
      dtype=[('Name', '<U30'), ('Population', '<i4'), ('Mass/tonnes', '<f4')])

In [301]:
for i, line in enumerate(data.split('\n')):
    list_of_data = line.strip().split()

    mass = float(list_of_data[-1])
    population = float(list_of_data[-2])
    name = ' '.join(list_of_data[:-2])
    print(np.array([(name, population, mass)], dtype=dt))
    ex57 = np.append(ex57, np.array([(name, population, mass)], dtype=dt))

[('Bowhead whale', 9000, 60.)]
[('Blue whale', 20000, 120.)]
[('Fin whale', 100000, 70.)]
[('Pacific white-sided dolphin', 1000000, 0.15)]
[('Killer whale', 100000, 4.5)]
[('Sperm whale', 2000000, 50.)]
[('North Atlantic right whale', 300, 75.)]
[('Southern right whale', 7000, 70.)]


In [302]:
ex57

array([('Bowhead whale',    9000,  60.  ),
       ('Blue whale',   20000, 120.  ), ('Fin whale',  100000,  70.  ),
       ('Pacific white-sided dolphin', 1000000,   0.15),
       ('Killer whale',  100000,   4.5 ),
       ('Sperm whale', 2000000,  50.  ),
       ('North Atlantic right whale',     300,  75.  ),
       ('Southern right whale',    7000,  70.  )],
      dtype=[('Name', '<U30'), ('Population', '<i4'), ('Mass/tonnes', '<f4')])

In [303]:
ex57.sort(order=['Mass/tonnes'])
ex57

array([('Pacific white-sided dolphin', 1000000,   0.15),
       ('Killer whale',  100000,   4.5 ),
       ('Sperm whale', 2000000,  50.  ),
       ('Bowhead whale',    9000,  60.  ), ('Fin whale',  100000,  70.  ),
       ('Southern right whale',    7000,  70.  ),
       ('North Atlantic right whale',     300,  75.  ),
       ('Blue whale',   20000, 120.  )],
      dtype=[('Name', '<U30'), ('Population', '<i4'), ('Mass/tonnes', '<f4')])

In [308]:
ex57.sort(order=['Population'])
ex57

array([('North Atlantic right whale',     300,  75.  ),
       ('Southern right whale',    7000,  70.  ),
       ('Bowhead whale',    9000,  60.  ),
       ('Blue whale',   20000, 120.  ), ('Fin whale',  100000,  70.  ),
       ('Killer whale',  100000,   4.5 ),
       ('Pacific white-sided dolphin', 1000000,   0.15),
       ('Sperm whale', 2000000,  50.  )],
      dtype=[('Name', '<U30'), ('Population', '<i4'), ('Mass/tonnes', '<f4')])

In [310]:
np.searchsorted(ex57['Population'], 100000)

4

In [305]:
ex57.sort(order=['Mass/tonnes','Population'])
ex57

array([('Pacific white-sided dolphin', 1000000,   0.15),
       ('Killer whale',  100000,   4.5 ),
       ('Sperm whale', 2000000,  50.  ),
       ('Bowhead whale',    9000,  60.  ),
       ('Southern right whale',    7000,  70.  ),
       ('Fin whale',  100000,  70.  ),
       ('North Atlantic right whale',     300,  75.  ),
       ('Blue whale',   20000, 120.  )],
      dtype=[('Name', '<U30'), ('Population', '<i4'), ('Mass/tonnes', '<f4')])

In [307]:
np.searchsorted(ex57['Mass/tonnes'], 100000)

8

In [311]:
!dir

 Volume in drive D is Documents
 Volume Serial Number is 8DBE-F730

 Directory of D:\Projects\ExperisAcademy\Exercises

04.12.2019  15:33    <DIR>          .
04.12.2019  15:33    <DIR>          ..
04.12.2019  09:01    <DIR>          .ipynb_checkpoints
27.11.2019  09:13    <DIR>          Adventure_game
04.12.2019  15:33            32,254 Basic Array Creation.ipynb
20.11.2019  11:58             7,564 BrainFuck_algorithm.ipynb
03.12.2019  09:11    <DIR>          Classes
26.11.2019  14:37    <DIR>          IO
01.12.2019  15:54    <DIR>          MP_Library
04.12.2019  13:52    <DIR>          OOP
01.12.2019  10:30    <DIR>          OS
26.11.2019  11:31    <DIR>          Project_Gutenberg
26.11.2019  16:30    <DIR>          Try-Except
24.11.2019  16:48             6,762 Untitled.ipynb
25.11.2019  16:50             4,572 Untitled1.ipynb
               4 File(s)         51,152 bytes
              11 Dir(s)  41,978,736,640 bytes free


In [314]:
!type Untitled.ipynb

{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 277,
   "metadata": {},
   "outputs": [],
   "source": [
    "def chess_board(N: int, queen_positions:list = []):\n",
    "    \n",
    "    # Draw a board:\n",
    "    board = [(x, y) for x in range(N) for y in range(N)]\n",
    "    \n",
    "    # Delete unsutable cells:\n",
    "    for queen_x, queen_y in queen_positions:\n",
    "        # Delete vertical lines:\n",
    "        [board.remove((queen_x, y)) for y in range(N)]\n",
    "        \n",
    "        # Delete horizontal lines:\n",
    "        [board.remove((x, queen_y)) for x in range(N)]\n",
    "        \n",
    "        # Delete first diagonals:\n",
    "        [board.remove((x, x - queen_y)) for x in range(N) if (x, x - queen_y) in board]\n",
    "        [board.remove((x, x + queen_y)) for x in range(N) if (x, x + queen_y) in board]\n",
    "        [board.remove((y, y - queen_x)) for y in range(N) if (y, y - queen_x) in board]\n",
    "        [boar

In [317]:
!help

For more information on a specific command, type HELP command-name
ASSOC          Displays or modifies file extension associations.
ATTRIB         Displays or changes file attributes.
BREAK          Sets or clears extended CTRL+C checking.
BCDEDIT        Sets properties in boot database to control boot loading.
CACLS          Displays or modifies access control lists (ACLs) of files.
CALL           Calls one batch program from another.
CD             Displays the name of or changes the current directory.
CHCP           Displays or sets the active code page number.
CHDIR          Displays the name of or changes the current directory.
CHKDSK         Checks a disk and displays a status report.
CHKNTFS        Displays or modifies the checking of disk at boot time.
CLS            Clears the screen.
CMD            Starts a new instance of the Windows command interpreter.
COLOR          Sets the default console foreground and background colors.
COMP           Compares the contents of two file

In [318]:
!cd

D:\Projects\ExperisAcademy\Exercises


In [319]:
!echo This is a test > test.txt

In [2]:
!dir

 Volume in drive D is Documents
 Volume Serial Number is 8DBE-F730

 Directory of D:\Projects\ExperisAcademy\Exercises

04.12.2019  16:35    <DIR>          .
04.12.2019  16:35    <DIR>          ..
04.12.2019  09:01    <DIR>          .ipynb_checkpoints
27.11.2019  09:13    <DIR>          Adventure_game
04.12.2019  16:35            53,798 Basic Array Creation.ipynb
20.11.2019  11:58             7,564 BrainFuck_algorithm.ipynb
03.12.2019  09:11    <DIR>          Classes
26.11.2019  14:37    <DIR>          IO
01.12.2019  15:54    <DIR>          MP_Library
04.12.2019  13:52    <DIR>          OOP
01.12.2019  10:30    <DIR>          OS
26.11.2019  11:31    <DIR>          Project_Gutenberg
04.12.2019  16:27                17 test.txt
26.11.2019  16:30    <DIR>          Try-Except
24.11.2019  16:48             6,762 Untitled.ipynb
25.11.2019  16:50             4,572 Untitled1.ipynb
               5 File(s)         72,713 bytes
              11 Dir(s)  41,978,712,064 bytes free


In [321]:
!type test.txt

This is a test 


In [322]:
%cd OOP

D:\Projects\ExperisAcademy\Exercises\OOP


In [1]:
!dir

 Volume in drive D is Documents
 Volume Serial Number is 8DBE-F730

 Directory of D:\Projects\ExperisAcademy\Exercises

04.12.2019  16:35    <DIR>          .
04.12.2019  16:35    <DIR>          ..
04.12.2019  09:01    <DIR>          .ipynb_checkpoints
27.11.2019  09:13    <DIR>          Adventure_game
04.12.2019  16:35            53,798 Basic Array Creation.ipynb
20.11.2019  11:58             7,564 BrainFuck_algorithm.ipynb
03.12.2019  09:11    <DIR>          Classes
26.11.2019  14:37    <DIR>          IO
01.12.2019  15:54    <DIR>          MP_Library
04.12.2019  13:52    <DIR>          OOP
01.12.2019  10:30    <DIR>          OS
26.11.2019  11:31    <DIR>          Project_Gutenberg
04.12.2019  16:27                17 test.txt
26.11.2019  16:30    <DIR>          Try-Except
24.11.2019  16:48             6,762 Untitled.ipynb
25.11.2019  16:50             4,572 Untitled1.ipynb
               5 File(s)         72,713 bytes
              11 Dir(s)  41,978,712,064 bytes free


In [326]:
current_dir = !dir

[' Volume in drive D is Documents',
 ' Volume Serial Number is 8DBE-F730',
 '',
 ' Directory of D:\\Projects\\ExperisAcademy\\Exercises\\OOP',
 '',
 '04.12.2019  13:52    <DIR>          .',
 '04.12.2019  13:52    <DIR>          ..',
 '02.12.2019  12:15             1,437 binary_tree.py',
 '04.12.2019  09:01               785 Geometry.py',
 '04.12.2019  13:52             3,885 zoo.py',
 '03.12.2019  09:11               200 zoo_db.txt',
 '               4 File(s)          6,307 bytes',
 '               2 Dir(s)  41,978,716,160 bytes free']

In [3]:
!echo print('Hello') > test.py

In [4]:
!python test.py

Hello


In [6]:
name = 'test.py'
res = !python $name

In [8]:
!dir


 Volume in drive D is Documents
 Volume Serial Number is 8DBE-F730

 Directory of D:\Projects\ExperisAcademy\Exercises

04.12.2019  16:39    <DIR>          .
04.12.2019  16:39    <DIR>          ..
04.12.2019  09:01    <DIR>          .ipynb_checkpoints
27.11.2019  09:13    <DIR>          Adventure_game
04.12.2019  16:39            55,121 Basic Array Creation.ipynb
20.11.2019  11:58             7,564 BrainFuck_algorithm.ipynb
03.12.2019  09:11    <DIR>          Classes
26.11.2019  14:37    <DIR>          IO
01.12.2019  15:54    <DIR>          MP_Library
04.12.2019  13:52    <DIR>          OOP
01.12.2019  10:30    <DIR>          OS
26.11.2019  11:31    <DIR>          Project_Gutenberg
04.12.2019  16:36                17 test.py
04.12.2019  16:27                17 test.txt
26.11.2019  16:30    <DIR>          Try-Except
24.11.2019  16:48             6,762 Untitled.ipynb
25.11.2019  16:50             4,572 Untitled1.ipynb
               6 File(s)         74,053 bytes
              11 Dir(s) 

In [9]:
!mkdir temp_dir

In [10]:
%cd temp_dir

D:\Projects\ExperisAcademy\Exercises\temp_dir


In [11]:
!echo > output.txt
!echo > readme.txt

In [15]:
!dir /?

Displays a list of files and subdirectories in a directory.

DIR [drive:][path][filename] [/A[[:]attributes]] [/B] [/C] [/D] [/L] [/N]
  [/O[[:]sortorder]] [/P] [/Q] [/R] [/S] [/T[[:]timefield]] [/W] [/X] [/4]

  [drive:][path][filename]
              Specifies drive, directory, and/or files to list.

  /A          Displays files with specified attributes.
  attributes   D  Directories                R  Read-only files
               H  Hidden files               A  Files ready for archiving
               S  System files               I  Not content indexed files
               L  Reparse Points             O  Offline files
               -  Prefix meaning not
  /B          Uses bare format (no heading information or summary).
  /C          Display the thousand separator in file sizes.  This is the
              default.  Use /-C to disable display of separator.
  /D          Same as wide but files are list sorted by column.
  /L          Uses lowercase.
  /N          New long list fo

In [16]:
!dir *.txt

 Volume in drive D is Documents
 Volume Serial Number is 8DBE-F730

 Directory of D:\Projects\ExperisAcademy\Exercises\temp_dir

04.12.2019  16:41                13 output.txt
04.12.2019  16:41                13 readme.txt
               2 File(s)             26 bytes
               0 Dir(s)  41,978,707,968 bytes free


In [17]:
!cd ..

In [18]:
!dir

 Volume in drive D is Documents
 Volume Serial Number is 8DBE-F730

 Directory of D:\Projects\ExperisAcademy\Exercises\temp_dir

04.12.2019  16:41    <DIR>          .
04.12.2019  16:41    <DIR>          ..
04.12.2019  16:41                13 output.txt
04.12.2019  16:41                13 readme.txt
               2 File(s)             26 bytes
               2 Dir(s)  41,978,707,968 bytes free


In [19]:
%cd ..

D:\Projects\ExperisAcademy\Exercises


In [ ]:
!rmdir temp_dir /S

In [ ]:
!dir